// Generate app/data/players.ts from TheSportsDB (free key) and download each
// player's photo into public/players/ so the app stays fully self-contained
// (strict CSP: img-src 'self'). Run: npm run data:players
//
// The free API key is rate-limited (~per minute), so every call is throttled and
// retried with backoff, and progress is cached to disk - re-run any time to resume.
import { writeFile, readFile, mkdir } from "node:fs/promises";
import { TEAMS } from "../app/data/teams.ts";

const KEY = "3"; // TheSportsDB public/free test key
const BASE = `https://www.thesportsdb.com/api/v1/json/${KEY}`;
const CACHE = "scripts/.players-cache.json";
const OUT = "app/data/players.ts";
const IMG_DIR = "public/players";
const PER_TEAM = 10; // free key caps the roster at ~10, all with photos

// Search-name overrides for nations TheSportsDB files under a different label.
const ALIAS: Record<string, string> = {
  "United States": "USA",
  "Cabo Verde": "Cape Verde",
  Türkiye: "Turkey",
  "Côte d'Ivoire": "Ivory Coast",
  Curaçao: "Curacao",
  Czechia: "Czech Republic",
};

type Player = { name: string; pos: string; img: string };
type Cache = Record<string, Player[]>;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const slug = (s: string) =>
  s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

// Fetch JSON, retrying while the response is empty (rate-limited) with growing waits.
async function getJson(url: string, tries = 6): Promise<any> {
  for (let i = 0; i < tries; i++) {
    try {
      const res = await fetch(url);
      const text = await res.text();
      if (text && text.trim() && text.trim() !== "null") return JSON.parse(text);
    } catch {
      /* network blip - fall through to backoff */
    }
    await sleep(2500 + i * 2000);
  }
  return null;
}

async function download(url: string, dest: string): Promise<boolean> {
  for (let i = 0; i < 4; i++) {
    try {
      const res = await fetch(url);
      if (res.ok) {
        await writeFile(dest, Buffer.from(await res.arrayBuffer()));
        return true;
      }
    } catch {
      /* retry */
    }
    await sleep(1500);
  }
  return false;
}

async function loadCache(): Promise<Cache> {
  try {
    return JSON.parse(await readFile(CACHE, "utf8"));
  } catch {
    return {};
  }
}

async function resolveTeamId(name: string): Promise<string | null> {
  const q = encodeURIComponent(ALIAS[name] ?? name);
  const data = await getJson(`${BASE}/searchteams.php?t=${q}`);
  const soccer = (data?.teams ?? []).filter((t: any) => t.strSport === "Soccer");
  const national =
    soccer.find((t: any) => (t.strLeague ?? "").includes("World Cup")) ??
    soccer.find((t: any) => !t.strLeague || t.strLeague === "_No League") ??
    soccer[0];
  return national?.idTeam ?? null;
}

async function main() {
  await mkdir(IMG_DIR, { recursive: true });
  const cache = await loadCache();

  for (const team of TEAMS) {
    if (cache[team.name]?.length) {
      console.log(`✓ ${team.name} (cached, ${cache[team.name].length})`);
      continue;
    }
    const id = await resolveTeamId(team.name);
    if (!id) {
      console.log(`- ${team.name}: no team found`);
      cache[team.name] = [];
      await writeFile(CACHE, JSON.stringify(cache, null, 2));
      continue;
    }
    const data = await getJson(`${BASE}/lookup_all_players.php?id=${id}`);
    const raw = (data?.player ?? []).filter((p: any) => p.strThumb).slice(0, PER_TEAM);
    const players: Player[] = [];
    for (const p of raw) {
      const file = `${slug(team.name)}-${slug(p.strPlayer)}.jpg`;
      const ok = await download(`${p.strThumb}/small`, `${IMG_DIR}/${file}`);
      if (ok) players.push({ name: p.strPlayer, pos: p.strPosition || "", img: `/players/${file}` });
    }
    cache[team.name] = players;
    await writeFile(CACHE, JSON.stringify(cache, null, 2));
    console.log(`✓ ${team.name}: ${players.length} players`);
    await sleep(1500);
  }

  // Emit players.ts (only nations we actually got, alphabetical), keys quoted.
  const entries = TEAMS.map((t) => t.name)
    .filter((n) => cache[n]?.length)
    .sort();
  const body = entries
    .map(
      (n) =>
        `  ${JSON.stringify(n)}: [\n` +
        cache[n]
          .map((p) => `    { name: ${JSON.stringify(p.name)}, pos: ${JSON.stringify(p.pos)}, img: ${JSON.stringify(p.img)} },`)
          .join("\n") +
        `\n  ],`
    )
    .join("\n");

  const file = `// GENERATED by scripts/fetch-players.mts (npm run data:players) - do not hand-edit.
// Source: TheSportsDB. Photos are downloaded into public/players/ so the app stays
// self-contained under a strict CSP (img-src 'self').
export type Player = { name: string; pos: string; img: string };

export const PLAYERS: Record<string, Player[]> = {
${body}
};

export function playersFor(team: string): Player[] {
  return PLAYERS[team] ?? [];
}

// Nations we have a squad for (used to gate the Players tab + quiz).
export const TEAMS_WITH_PLAYERS: string[] = Object.keys(PLAYERS);

// Flat pool of every player tagged with its nation - the quiz draws from this.
export const PLAYER_POOL: { player: Player; team: string }[] = Object.entries(PLAYERS).flatMap(
  ([team, ps]) => ps.map((player) => ({ player, team }))
);
`;
  await writeFile(OUT, file);
  const total = entries.reduce((s, n) => s + cache[n].length, 0);
  console.log(`\nWrote ${OUT}: ${entries.length} nations, ${total} players.`);
}

main();
